### ISSUE TITLE
FetchError on TrRouting on long running batchrouting

### ISSUE THREAD

**Issue by greenscientist** [chairemobilite/transition#1011]
During a specific big batch calculation, we get the following error message. Calculation continue, but seems something that might be bad from the TrRouting side. 

2024-07-16T14:12:05.956561133Z FetchError: request to http://localhost:14000/v2/route?origin=-73.572,45.5061&destination=-73.1775,45.5308&scenario_id=27ef6b8a-af95-491b-8015-e59d67f81cc1&time_of_trip=57600&time_type=0&alternatives=true&min_waiting_time=180&max_access_travel_time=1200&max_egress_travel_time=1200&max_transfer_travel_time=1200&max_travel_time=14400&max_first_waiting_time=3600 failed, reason: socket hang up
2024-07-16T14:12:05.956604916Z     at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1491:11)
2024-07-16T14:12:05.956611874Z     at ClientRequest.emit (node:events:517:28)
2024-07-16T14:12:05.956616000Z     at Socket.socketOnEnd (node:_http_client:525:9)
2024-07-16T14:12:05.956619494Z     at Socket.emit (node:events:529:35)
2024-07-16T14:12:05.956622941Z     at endReadableNT (node:internal/streams/readable:1400:12)
2024-07-16T14:12:05.956626388Z     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
2024-07-16T14:12:05.956630402Z   type: 'system',
2024-07-16T14:12:05.956633899Z   errno: 'ECONNRESET',
2024-07-16T14:12:05.956637313Z   code: 'ECONNRESET'
2024-07-16T14:12:05.956640735Z }
2024-07-16T14:12:05.956644358Z FetchError: request to http://localhost:14000/v2/route?origin=-73.572,45.5061&destination=-73.1775,45.5308&scenario_id=27ef6b8a-af95-491b-8015-e59d67f81cc1&time_of_trip=57600&time_type=0&alternatives=true&min_waiting_time=180&max_access_travel_time=1200&max_egress_travel_time=1200&max_transfer_travel_time=1200&max_travel_time=14400&max_first_waiting_time=3600 failed, reason: socket hang up
2024-07-16T14:12:05.956647814Z     at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1491:11)
2024-07-16T14:12:05.956651390Z     at ClientRequest.emit (node:events:517:28)
2024-07-16T14:12:05.956654795Z     at Socket.socketOnEnd (node:_http_client:525:9)
2024-07-16T14:12:05.956658286Z     at Socket.emit (node:events:529:35)
2024-07-16T14:12:05.956661927Z     at endReadableNT (node:internal/streams/readable:1400:12)
2024-07-16T14:12:05.956665388Z     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
2024-07-16T14:12:05.956668740Z   type: 'system',
2024-07-16T14:12:05.956672196Z   errno: 'ECONNRESET',
2024-07-16T14:12:05.956675915Z   code: 'ECONNRESET'
2024-07-16T14:12:05.956679332Z }

**Comment by tahini** [comment]
During a specific calculation, this error happens around a missed checkpoint (though it is almost 1h30 later than the previous and next checkpoint. There may be a missing or misplaced try/catch when this happens. It should not miss the checkpoint, even if it happens.

**Comment by tahini** [comment]
After further investigation, this error occurs when trRouting is unresponsive, but in those cases, the faulty response is correctly saved in the results. The error itself should be better handled, now it results in a generic server error in the results and a log in the console. A fetch error should result in a transition error with proper code, handled by the caller.

The checkpoint miss is not related to the fetch error.

But we still need to investigate why trRouting becomes unresponsive like this sometimes. Are there too many requests ongoing at that moment?
