### ISSUE TITLE
Problem with socket hangup with upgrade to Node 20

### ISSUE THREAD

**Issue by greenscientist** [chairemobilite/transition#1052]
We are getting these error after attemping to run the system with Node 20: 

transition-www_1  | 2024-09-16T17:12:21.441422810Z FetchError: request to http://localhost:2000/node failed, reason: socket hang up
transition-www_1  | 2024-09-16T17:12:21.441489135Z     at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1491:11)
transition-www_1  | 2024-09-16T17:12:21.441507791Z     at ClientRequest.emit (node:events:519:28)
transition-www_1  | 2024-09-16T17:12:21.441523069Z     at Socket.socketOnEnd (node:_http_client:524:9)
transition-www_1  | 2024-09-16T17:12:21.441537958Z     at Socket.emit (node:events:531:35)
transition-www_1  | 2024-09-16T17:12:21.441552385Z     at endReadableNT (node:internal/streams/readable:1696:12)
transition-www_1  | 2024-09-16T17:12:21.441566892Z     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
transition-www_1  | 2024-09-16T17:12:21.441617508Z   type: 'system',
transition-www_1  | 2024-09-16T17:12:21.441632897Z   errno: 'ECONNRESET',
transition-www_1  | 2024-09-16T17:12:21.441647244Z   code: 'ECONNRESET'
transition-www_1  | 2024-09-16T17:12:21.441661591Z }
transition-www_1  | 2024-09-16T17:12:21.801362057Z FetchError: request to http://localhost:2000/node failed, reason: socket hang up
transition-www_1  | 2024-09-16T17:12:21.801415418Z     at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1491:11)
transition-www_1  | 2024-09-16T17:12:21.801433903Z     at ClientRequest.emit (node:events:519:28)
transition-www_1  | 2024-09-16T17:12:21.801449052Z     at Socket.socketOnEnd (node:_http_client:524:9)
transition-www_1  | 2024-09-16T17:12:21.801464080Z     at Socket.emit (node:events:531:35)
transition-www_1  | 2024-09-16T17:12:21.801478587Z     at endReadableNT (node:internal/streams/readable:1696:12)
transition-www_1  | 2024-09-16T17:12:21.801493135Z     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
transition-www_1  | 2024-09-16T17:12:21.801508083Z   type: 'system',
transition-www_1  | 2024-09-16T17:12:21.801522841Z   errno: 'ECONNRESET',
transition-www_1  | 2024-09-16T17:12:21.801537278Z   code: 'ECONNRESET'
transition-www_1  | 2024-09-16T17:12:21.801551565Z }

**Comment by tahini** [comment]
See if this is a variation of #1011 where we sometimes get fetch errors also in node 18 with trRouting.

**Comment by greenscientist** [comment]
Maybe #1054 will fix this?
