### ISSUE TITLE
Docker: Erreur ECONNREFUSED localhost:2000

### ISSUE THREAD

**Issue by brodyFlannigan** [chairemobilite/transition#780]
Bonjour!

J'ai un problème au niveau de la récupération et l'enregistrement de données dans le front-end lorsque j'utilise une installation de Transition avec Docker.

Lorsque j'essaie de créer un arrêt ou une ligne, l'erreur suivante apparait dans les logs du container:

```
TrError: cannot update cache file Line because of an error: FetchError: request to http://localhost:2000/line failed, reason: connect ECONNREFUSED 127.0.0.1:2000
2023-11-26 11:49:28     at /app/packages/transition-backend/lib/api/transitObjects.socketRoutes.js:185:31
2023-11-26 11:49:28     at Generator.throw (<anonymous>)
2023-11-26 11:49:28     at rejected (/app/packages/transition-backend/lib/api/transitObjects.socketRoutes.js:29:65)
2023-11-26 11:49:28     at runMicrotasks (<anonymous>)
2023-11-26 11:49:28     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
2023-11-26 11:49:28   code: 'SKTTRUP0001',
2023-11-26 11:49:28   localizedMessage: 'CacheCouldNotBeUpdatedBecauseError'
2023-11-26 11:49:28 }
```

## Pour reproduire:
1. Suivre à la lettre les instructions [ici](https://github.com/chairemobilite/transition/blob/main/docs/runWithDocker.md)
2. Se connecter (login)
3. Tenter de créer un arrêt et surveiller les logs. L'arrêt disparaîtra de la carte. Cependant, lorsque le container du front-end est relancé, l'arrêt créé apparaît, mais il est impossible d'interragir avec (c'est-à-dire que je ne peux pas aller modifier ses attributs, etc.). Ceci est également le cas avec une ligne (mais pas avec une agence ou un service, curieusement).

**Comment by tahini** [comment]
Ce message d'erreur est le signe que le serveur json2capnp ne roule pas. Avec docker, il est parti automatiquement au démarrage, mais je crois que le répertoire doit peut-être être crée manuellement avant? Je ne suis pas très familière avec cette façon de rouler, mais voici ce que dit le Dockerfile à la fin:

```
# Start json2capnp -> Relies on manually creating cache directory before
# Start Node app
CMD sh -c "cd services/json2capnp && pwd && ./json2capnp 2000 /app/examples/runtime/cache/demo_transition > /app/json2capnp.log &" && yarn build:prod && yarn start
```

**Comment by greenscientist** [comment]
@tahini , voudrait-on mettre à jour les instructions ou faire en sorte que ça soit fait/géré automatiquement?

**Comment by tahini** [comment]
À court terme, il faudrait mettre à jour les instructions si on est sûrs que ça fonctionne. @brodyFlannigan serait-il possible de confirmer que la création du dossier fixe ce problème?

Mais on veut que ce soit géré automatiquement, on veut peut-être aussi ne pas avoir à dépendre de cette cache. On verra ce qu'on veut le plus, il faudrait tester les performances de mettre les noeuds transférables dans la BD au lieu de juste en cache...

**Comment by brodyFlannigan** [comment]
J'imagine que la création du dossier devrait régler le problème. Cependant, je ne suis pas en mesure de confirmer cela puisque je ne suis pas certain où il faut créer le dossier...

Serait-il possible de m'indiquer où le dossier doit être créé dans le container? Je ferai l'essai et je vous reviendrai.

**Comment by brodyFlannigan** [comment]
Petit update: J'ai réussi à trouver où créer le répertoire et en effet cela à réglé le problème.

Voici ce que j'ai fait:

1. Ouvrir le terminal dans Docker desktop pour le container transition-www (note: le terminal ouvre dans le répertoire `/app`
2. `cd examples`
3. `mkdir runtime`
4. `cd runtime`
5. `mkdir cache`
6. `cd cache`
7. `mkdir demo_transition`
8. Redémarrer le container avec l'interface docker desktop.
9. Admirer le fait que ça fonctionne.

Je suis absolument certain qu'il existe une façon plus simple de faire ça, mais j'ai préféré être prudent et y aller une étape à la fois...

**Comment by tahini** [comment]
Merci, on va confirmer l'emplacement hors docker où créer le répertoire et on pourra mettre à jour la documentation

**Comment by greenscientist** [comment]
C'est quand même étrange que ça n'aille pas été créé comme il faut la première fois. 

@brodyFlannigan, est-ce possible de nous indiquer si tu roules sous Windows, Mac ou Linux ?

**Comment by brodyFlannigan** [comment]
Je roule Mac avec puce M1.

Docker Desktop me montre un avis comme quoi la performance pourrait être sous-optimale car Transition est concu pour les puces ARM64, mais je ne remarque aucune dégradation visible. Tout roule très bien et très rapidement (quoique ma base de données est très petite, juste quelques lignes et environ 1800 arrêts...)

**Comment by greenscientist** [comment]
On devrait considérer faire un build docker pour ARM. Ca devrait bien fonctionner.

**Comment by greenscientist** [comment]
Removed json2capnp, now we have direct Rust binding
