### ISSUE TITLE
API : Can't access api/v1/nodes 

### ISSUE THREAD

**Issue by tibobliss** [chairemobilite/transition#990]
Scenarios and paths are accessible, but not nodes. Also goes for the QGIS plugin: we can fetch paths but nothing happens when fetching nodes.

### THIS WORKS
![image](https://github.com/chairemobilite/transition/assets/5404176/48fe7421-d100-4786-a494-facf99631dbc)
![image](https://github.com/chairemobilite/transition/assets/5404176/3bcdcc93-d82b-4841-b87d-20c6df875d00)

### BUT THIS DOESN'T

![image](https://github.com/chairemobilite/transition/assets/5404176/71c7a524-1847-4fd0-819f-fd82b8dfafb9)
![image](https://github.com/chairemobilite/transition/assets/5404176/73e535c7-e820-436e-9422-4a84ab7c18ac)

**Comment by greenscientist** [comment]
Here's the stack trace: 
TypeError: Cannot read properties of undefined (reading 'map')
    at /app/packages/transition-backend/lib/api/public/NodesAPIResponse.js:19:58
    at Array.map (<anonymous>)
    at NodesAPIResponse.createResponse (/app/packages/transition-backend/lib/api/public/NodesAPIResponse.js:11:38)
    at new APIResponseBase (/app/packages/transition-backend/lib/api/public/APIResponseBase.js:11:30)
    at new NodesAPIResponse (/app/packages/transition-backend/lib/api/public/NodesAPIResponse.js:7:1)
    at /app/packages/transition-backend/lib/api/public.routes.js:146:30
    at Generator.next (<anonymous>)
    at fulfilled (/app/packages/transition-backend/lib/api/public.routes.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
